---
# Decompression related source packages
# 2018-04-07 22:56 by liubaobao at WDTY company

- name: Decompression related php source packages
  unarchive: src=/tmp/{{ NGINX }}.tgz dest=/tmp/ copy=no
  ignore_errors: True
  tags: unarchive
